export interface MenuItem {
  id: string;
  name: string;
  category: string;
  price: string;
  priceNum: number;
  isVeg?: boolean;
  isSpicy?: boolean;
  isSignature?: boolean;
  description?: string;
  portion?: string;
  image?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  badge?: string;
  count?: number;
}

export const MENU_CATEGORIES: MenuCategory[] = [
  { id: "all", name: "Full Menu" },
  { id: "breakfast", name: "Breakfast", badge: "Morning Special" },
  { id: "mocktails", name: "Mocktails", badge: "Signature Drinks" },
  { id: "veg-pizza", name: "Veg Pizza" },
  { id: "non-veg-pizza", name: "Non-Veg Pizza" },
  { id: "pasta", name: "Pasta" },
  { id: "tit-bites", name: "Tit Bites & Snacks" },
  { id: "burger-sandwich", name: "Burgers & Sandwiches" },
  { id: "sizzler", name: "Sizzlers" },
  { id: "noodles-rice-veg", name: "Noodles & Rice (Veg)" },
  { id: "noodles-rice-non-veg", name: "Noodles & Rice (Non-Veg)" },
  { id: "soups", name: "Soups" },
  { id: "chinese-veg", name: "Chinese Veg" },
  { id: "chinese-non-veg", name: "Chinese Non-Veg" },
  { id: "fish", name: "Fish Specialties", badge: "Chef Special" },
  { id: "tandoori-veg", name: "Tandoori Snacks Veg" },
  { id: "fish-tandoori", name: "Fish Tandoori" },
  { id: "main-veg", name: "Main Course Veg" },
  { id: "main-non-veg", name: "Main Course Non-Veg", badge: "House Special" },
  { id: "mutton", name: "Mutton Special" },
  { id: "rice-biryani", name: "Rice & Biryani" },
  { id: "salad-raita", name: "Salad & Raita" },
  { id: "breads", name: "Assorted Breads", badge: "Clay Oven" },
  { id: "desserts", name: "Desserts & Shakes" },
  { id: "bar-beverages", name: "Lounge Bar & Drinks" },
];

export const MENU_ITEMS: MenuItem[] = [
  // ── BREAKFAST (Page 1) ──────────────────────
  {
    id: "bf-1",
    name: "Butter Toast",
    category: "breakfast",
    price: "₹79",
    priceNum: 79,
    isVeg: true,
    description: "Crispy golden toasted bread slices topped with generous melted butter.",
  },
  {
    id: "bf-2",
    name: "Channa Bhatura (2pcs.) with Pickle",
    category: "breakfast",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    isSignature: true,
    description: "Fluffy puffed bhaturas served with spicy Amritsari channa and house pickle.",
  },
  {
    id: "bf-3",
    name: "Mix Parantha with Curd with Pickle",
    category: "breakfast",
    price: "₹99",
    priceNum: 99,
    isVeg: true,
    description: "Traditional Punjabi stuffed parantha served with thick fresh curd and pickle.",
  },
  {
    id: "bf-4",
    name: "Plain Omelette",
    category: "breakfast",
    price: "₹79",
    priceNum: 79,
    isVeg: false,
    description: "Classic light and fluffy pan-whipped eggs cooked to perfection.",
  },
  {
    id: "bf-5",
    name: "Omelette Masala",
    category: "breakfast",
    price: "₹99",
    priceNum: 99,
    isVeg: false,
    isSpicy: true,
    description: "Whisked eggs tossed with chopped green chilies, onions, tomatoes and Indian herbs.",
  },
  {
    id: "bf-6",
    name: "Omelette with Slice",
    category: "breakfast",
    price: "₹119",
    priceNum: 119,
    isVeg: false,
    description: "Freshly made masala or plain omelette served with two buttered bread slices.",
  },
  {
    id: "bf-7",
    name: "Boiled Egg (2pcs.)",
    category: "breakfast",
    price: "₹69",
    priceNum: 69,
    isVeg: false,
    description: "Fresh farm eggs boiled and served with black pepper and chaat masala.",
  },

  // ── MOCKTAILS (Page 1) ──────────────────────
  {
    id: "mock-1",
    name: "Lovers Passion",
    category: "mocktails",
    price: "₹139",
    priceNum: 139,
    isVeg: true,
    isSignature: true,
    description: "Exotic passion fruit blend layered with berry syrup and sparkling soda.",
  },
  {
    id: "mock-2",
    name: "Blue Ocean",
    category: "mocktails",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    isSignature: true,
    description: "Vibrant blue curaçao layered cooler with fresh mint, lime slices and crushed ice.",
    image: "/uploads/gtg-mocktail-drink.jpg",
  },
  {
    id: "mock-3",
    name: "Virgin Mojito",
    category: "mocktails",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Crisp muddled fresh garden mint, zesty lime wedges and effervescent soda.",
  },
  {
    id: "mock-4",
    name: "Orange Delight",
    category: "mocktails",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Chilled citrus orange crush with a refreshing splash of fizz.",
  },
  {
    id: "mock-5",
    name: "Mango Delight",
    category: "mocktails",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Luscious alphonso mango purée blended into a chilled summer cooler.",
  },
  {
    id: "mock-6",
    name: "Pink Lady",
    category: "mocktails",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Sweet strawberry and rose infused creamy cooler with chilled sparkling soda.",
  },

  // ── VEG PIZZA (Page 1) ──────────────────────
  {
    id: "vp-1",
    name: "Margherita Cheese",
    category: "veg-pizza",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    description: "Herb seasoned Italian marinara base generously blanketed with melted mozzarella.",
  },
  {
    id: "vp-2",
    name: "Onion, Capsicum, Tomato",
    category: "veg-pizza",
    price: "₹159",
    priceNum: 159,
    isVeg: true,
    description: "Fresh crisp farm onions, crunchy green bell peppers and ripe juicy tomatoes.",
  },
  {
    id: "vp-3",
    name: "Farm House",
    category: "veg-pizza",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    isSignature: true,
    description: "Loaded with sweet corn, mushrooms, crisp bell peppers, onions and mozzarella.",
  },
  {
    id: "vp-4",
    name: "Get 2 Gather Special Pizza",
    category: "veg-pizza",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    isSignature: true,
    description: "Chef's signature crust with tandoori paneer cubes, olives, jalapenos, mushrooms & secret spices.",
  },
  {
    id: "vp-5",
    name: "Cheese Chilly Pizza",
    category: "veg-pizza",
    price: "₹189",
    priceNum: 189,
    isVeg: true,
    isSpicy: true,
    description: "Spicy Indo-Chinese seasoned cheese cubes, hot green chilies and onions.",
  },
  {
    id: "vp-6",
    name: "Mushroom Cheese Pizza",
    category: "veg-pizza",
    price: "₹189",
    priceNum: 189,
    isVeg: true,
    description: "Tender sautéed button mushrooms smothered under golden melted cheese.",
  },

  // ── NON-VEG PIZZA (Page 2) ──────────────────
  {
    id: "nvp-1",
    name: "Chilly Chicken Pizza",
    category: "non-veg-pizza",
    price: "₹229",
    priceNum: 229,
    isVeg: false,
    isSpicy: true,
    isSignature: true,
    description: "Spicy diced chicken tossed with onions and capsicum on a cheesy baked crust.",
  },
  {
    id: "nvp-2",
    name: "Non Veg Farm House",
    category: "non-veg-pizza",
    price: "₹229",
    priceNum: 229,
    isVeg: false,
    description: "Tender chicken tikka chunks, mushrooms, crunchy peppers and rich mozzarella.",
  },

  // ── PASTA (Page 2) ──────────────────────────
  {
    id: "pasta-1",
    name: "White Sauce Pasta",
    category: "pasta",
    price: "Veg ₹209 / Non-Veg ₹269",
    priceNum: 209,
    description: "Silky Alfredo pasta simmered with garlic butter, fresh cream and herbs.",
  },
  {
    id: "pasta-2",
    name: "Red Sauce Pasta",
    category: "pasta",
    price: "Veg ₹209 / Non-Veg ₹269",
    priceNum: 209,
    description: "Penne tossed in spicy Italian tomato marinara with garlic and basil.",
  },
  {
    id: "pasta-3",
    name: "Mix Sauce Pasta",
    category: "pasta",
    price: "Veg ₹209 / Non-Veg ₹269",
    priceNum: 209,
    isSignature: true,
    description: "The best of both worlds: creamy pink sauce pasta with rich cheese and seasoning.",
  },
  {
    id: "pasta-4",
    name: "Pasta with Garlic Breads",
    category: "pasta",
    price: "Veg ₹229 / Non-Veg ₹369",
    priceNum: 229,
    description: "Choice of pasta served alongside oven-toasted buttery garlic breads.",
  },

  // ── TIT BITES (Page 2) ──────────────────────
  {
    id: "tb-1",
    name: "Masala Papad",
    category: "tit-bites",
    price: "₹119",
    priceNum: 119,
    isVeg: true,
    description: "Crispy roasted papad topped with diced onions, tomatoes, coriander and tangy chaat masala.",
  },
  {
    id: "tb-2",
    name: "Roasted Papad (2pcs.)",
    category: "tit-bites",
    price: "₹79",
    priceNum: 79,
    isVeg: true,
    description: "Light oven-roasted papad crisps.",
  },
  {
    id: "tb-3",
    name: "Fried Papad (2pcs.)",
    category: "tit-bites",
    price: "₹89",
    priceNum: 89,
    isVeg: true,
    description: "Golden deep-fried crunchy lentil papads.",
  },
  {
    id: "tb-4",
    name: "Peanut Masala",
    category: "tit-bites",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    description: "Crunchy roasted peanuts tossed with finely chopped veggies, lime juice and masala.",
  },
  {
    id: "tb-5",
    name: "Channa Chat",
    category: "tit-bites",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    description: "Tangy boiled chickpeas seasoned with lemon, spices and crunchy onions.",
  },
  {
    id: "tb-6",
    name: "Aloo Channa Chat",
    category: "tit-bites",
    price: "₹159",
    priceNum: 159,
    isVeg: true,
    description: "Diced potatoes and chickpeas tossed with sweet chutney and spicy seasoning.",
  },
  {
    id: "tb-7",
    name: "French Fries",
    category: "tit-bites",
    price: "₹179",
    priceNum: 179,
    isVeg: true,
    description: "Crispy golden salted potato fries served piping hot with tomato ketchup.",
  },
  {
    id: "tb-8",
    name: "Paneer Pakora",
    category: "tit-bites",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    description: "Thick cottage cheese batons coated in spiced gram flour batter and fried golden.",
  },
  {
    id: "tb-9",
    name: "Veg Pakora",
    category: "tit-bites",
    price: "₹269",
    priceNum: 269,
    isVeg: true,
    description: "Crisp assorted vegetable fritters served with mint coriander dip.",
  },
  {
    id: "tb-10",
    name: "Fresh Paneer",
    category: "tit-bites",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Soft fresh malai paneer cubes with chaat masala.",
  },
  {
    id: "tb-11",
    name: "Italian Finger",
    category: "tit-bites",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    description: "Crumb-coated herb fingers filled with creamy Italian vegetables.",
  },
  {
    id: "tb-12",
    name: "Cheese Finger",
    category: "tit-bites",
    price: "₹269",
    priceNum: 269,
    isVeg: true,
    isSignature: true,
    description: "Gooey mozzarella cheese sticks crumbed and fried with herbs.",
  },
  {
    id: "tb-13",
    name: "Saute Veg.",
    category: "tit-bites",
    price: "₹239",
    priceNum: 239,
    isVeg: true,
    description: "Fresh garden vegetables tossed in butter and cracked black pepper.",
  },
  {
    id: "tb-14",
    name: "Cream of Boiled Saute Corn",
    category: "tit-bites",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Sweet American corn kernels tossed in fresh cream and butter.",
  },

  // ── BURGER AND SANDWICH (Page 2) ────────────
  {
    id: "bs-1",
    name: "Veg Burger",
    category: "burger-sandwich",
    price: "₹99",
    priceNum: 99,
    isVeg: true,
    description: "Crispy seasoned vegetable patty with lettuce, tomatoes, mayo in a sesame bun.",
  },
  {
    id: "bs-2",
    name: "Cheese Burger",
    category: "burger-sandwich",
    price: "₹119",
    priceNum: 119,
    isVeg: true,
    description: "Classic veggie burger topped with a melted cheddar cheese slice.",
  },
  {
    id: "bs-3",
    name: "Chicken Burger",
    category: "burger-sandwich",
    price: "₹169",
    priceNum: 169,
    isVeg: false,
    description: "Juicy chicken patty grilled to perfection with spicy mayo and lettuce.",
  },
  {
    id: "bs-4",
    name: "Veg Sandwich",
    category: "burger-sandwich",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Fresh cucumber, tomato and mint chutney stuffed between soft bread slices.",
  },
  {
    id: "bs-5",
    name: "Veg Grilled Sandwich",
    category: "burger-sandwich",
    price: "₹139",
    priceNum: 139,
    isVeg: true,
    description: "Toasted golden brown with spiced vegetable filling.",
  },
  {
    id: "bs-6",
    name: "Cheese Sandwich",
    category: "burger-sandwich",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    description: "Generous cheese filling melted between soft bread slices.",
  },
  {
    id: "bs-7",
    name: "Cheese Grilled Sandwich",
    category: "burger-sandwich",
    price: "₹179",
    priceNum: 179,
    isVeg: true,
    isSignature: true,
    description: "Crispy grilled bread bursting with gooey melted cheese and herbs.",
  },

  // ── SIZZLER (Page 2) ────────────────────────
  {
    id: "sz-1",
    name: "Veg. Sizzler (Chinese / Continental)",
    category: "sizzler",
    price: "₹329",
    priceNum: 329,
    isVeg: true,
    isSignature: true,
    description: "Smoking hot sizzler plate with noodles/rice, cutlets, grilled veggies and sizzling sauce.",
  },
  {
    id: "sz-2",
    name: "Non Veg. Sizzler (Chinese / Continental)",
    category: "sizzler",
    price: "₹429",
    priceNum: 429,
    isVeg: false,
    isSignature: true,
    description: "Sizzling chicken steak with fried rice/noodles, buttered veggies and signature glaze.",
  },

  // ── NOODLES & RICE VEG (Page 2) ─────────────
  {
    id: "nrv-1",
    name: "Veg Noodles",
    category: "noodles-rice-veg",
    price: "₹189",
    priceNum: 189,
    isVeg: true,
    description: "Wok-tossed noodles with shredded cabbage, carrots, capsicum and light soy sauce.",
  },
  {
    id: "nrv-2",
    name: "Veg Hakka Noodle",
    category: "noodles-rice-veg",
    price: "₹199",
    priceNum: 199,
    isVeg: true,
    description: "Indo-Chinese street style Hakka noodles tossed with spring onions and garlic.",
  },
  {
    id: "nrv-3",
    name: "Singapore Noodles",
    category: "noodles-rice-veg",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    isSpicy: true,
    description: "Curry-flavoured thin noodles tossed with crispy vegetables.",
  },
  {
    id: "nrv-4",
    name: "Veg Fried Rice",
    category: "noodles-rice-veg",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    description: "Long grain aromatic rice stir-fried with diced farm fresh vegetables.",
  },
  {
    id: "nrv-5",
    name: "Veg Choupsy",
    category: "noodles-rice-veg",
    price: "₹239",
    priceNum: 239,
    isVeg: true,
    description: "Crispy fried noodles topped with sweet and sour tangy vegetable sauce.",
  },

  // ── NOODLES & RICE NON-VEG (Page 2) ─────────
  {
    id: "nrnv-1",
    name: "Chicken Noodles",
    category: "noodles-rice-non-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: false,
    description: "Egg noodles tossed with succulent chicken shreds and crisp vegetables.",
  },
  {
    id: "nrnv-2",
    name: "Chicken Hakka Noodles",
    category: "noodles-rice-non-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: false,
    description: "Wok tossed hakka style noodles with garlic, shredded chicken and veggies.",
  },
  {
    id: "nrnv-3",
    name: "Chicken Singapore Noodles",
    category: "noodles-rice-non-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: false,
    isSpicy: true,
    description: "Spicy seasoned Singapore style noodles with tender chicken bites.",
  },
  {
    id: "nrnv-4",
    name: "Chicken Fried Rice",
    category: "noodles-rice-non-veg",
    price: "₹239",
    priceNum: 239,
    isVeg: false,
    description: "Classic Chinese wok-fried rice with tender chicken cubes and spring onions.",
  },
  {
    id: "nrnv-5",
    name: "Egg Fried Rice",
    category: "noodles-rice-non-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: false,
    description: "Aromatic basmati rice tossed with scrambled egg ribbon and soy sauce.",
  },
  {
    id: "nrnv-6",
    name: "Egg Noodles",
    category: "noodles-rice-non-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: false,
    description: "Soft noodles tossed with fluffy egg strips and fresh julienned veggies.",
  },
  {
    id: "nrnv-7",
    name: "American Choupsy",
    category: "noodles-rice-non-veg",
    price: "₹339",
    priceNum: 339,
    isVeg: false,
    isSignature: true,
    description: "Crispy fried noodle nest topped with sweet & sour chicken gravy and fried egg.",
  },

  // ── SOUPS (Page 3) ──────────────────────────
  {
    id: "sp-1",
    name: "Veg Manchow Soup",
    category: "soups",
    price: "Veg ₹109 / Non-Veg ₹159",
    priceNum: 109,
    isSpicy: true,
    description: "Spicy dark broth with mushrooms, garlic, coriander and topped with crispy fried noodles.",
  },
  {
    id: "sp-2",
    name: "Sweet Corn Soup",
    category: "soups",
    price: "Veg ₹119 / Non-Veg ₹139",
    priceNum: 119,
    description: "Thick creamy sweet corn broth seasoned with mild butter and white pepper.",
  },
  {
    id: "sp-3",
    name: "Hot N Sour Soup",
    category: "soups",
    price: "Veg ₹109 / Non-Veg ₹139",
    priceNum: 109,
    isSpicy: true,
    description: "Authentic spicy and tangy Chinese broth with black vinegar and chili peppers.",
  },
  {
    id: "sp-4",
    name: "Talumein Soup",
    category: "soups",
    price: "Veg ₹99 / Non-Veg ₹139",
    priceNum: 99,
    description: "Warm soothing noodle soup with diced veggies and subtle seasoning.",
  },
  {
    id: "sp-5",
    name: "Lemon Coriander Soup",
    category: "soups",
    price: "Veg ₹99 / Non-Veg ₹139",
    priceNum: 99,
    description: "Refreshing zesty broth loaded with fresh coriander greens and lemon juice.",
  },
  {
    id: "sp-6",
    name: "Veg Clear Soup",
    category: "soups",
    price: "Veg ₹99 / Non-Veg ₹139",
    priceNum: 99,
    description: "Healthy light vegetable stock with finely diced garden greens.",
  },
  {
    id: "sp-7",
    name: "Cream of Tomato",
    category: "soups",
    price: "₹99",
    priceNum: 99,
    isVeg: true,
    description: "Rich velvety ripe tomato soup finished with fresh cream and crispy croutons.",
  },
  {
    id: "sp-8",
    name: "Cream of Mushroom",
    category: "soups",
    price: "₹119",
    priceNum: 119,
    isVeg: true,
    description: "Pureed button mushrooms simmered with herbs and a drizzle of fresh cream.",
  },
  {
    id: "sp-9",
    name: "Cream of Chicken Soup",
    category: "soups",
    price: "₹139",
    priceNum: 139,
    isVeg: false,
    description: "Luxurious creamy chicken broth with finely shredded chicken breast.",
  },

  // ── CHINESE VEG (Page 3) ────────────────────
  {
    id: "cv-1",
    name: "Veg Balls in Hot Garlic Sauce",
    category: "chinese-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    isSpicy: true,
    description: "Minced vegetable dumplings simmered in a zesty fiery hot garlic sauce.",
  },
  {
    id: "cv-2",
    name: "Crispy Corn Salt n Pepper",
    category: "chinese-veg",
    price: "₹269",
    priceNum: 269,
    isVeg: true,
    description: "Sweet corn kernels tossed with cracked black pepper, salt, green chilies and onions.",
  },
  {
    id: "cv-3",
    name: "Crispy Veg",
    category: "chinese-veg",
    price: "₹269",
    priceNum: 269,
    isVeg: true,
    description: "Batter fried julienned veggies glazed with tangy oriental seasoning.",
  },
  {
    id: "cv-4",
    name: "Cheese Chilly Singapore (Dry / Gravy)",
    category: "chinese-veg",
    price: "₹269",
    priceNum: 269,
    isVeg: true,
    isSpicy: true,
    description: "Cottage cheese cubes tossed in Singaporean chili glaze with peppers and scallions.",
  },
  {
    id: "cv-5",
    name: "Get 2 Gather Special Snack",
    category: "chinese-veg",
    price: "₹379",
    priceNum: 379,
    isVeg: true,
    isSignature: true,
    description: "House special mixed appetizer platter featuring chef's exclusive crispy delicacies.",
  },
  {
    id: "cv-6",
    name: "Veg Manchurian (Dry / Gravy)",
    category: "chinese-veg",
    price: "₹239",
    priceNum: 239,
    isVeg: true,
    description: "Deep fried vegetable rounds coated in rich ginger-soy sauce.",
  },
  {
    id: "cv-7",
    name: "Veg Bullets",
    category: "chinese-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Spiced paneer and vegetable bullet croquettes fried golden crisp.",
  },
  {
    id: "cv-8",
    name: "Veg Spring Rolls",
    category: "chinese-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Crispy fried pastry rolls stuffed with shredded veggies, served with sweet chili dip.",
  },
  {
    id: "cv-9",
    name: "Mushroom Chilly (Dry / Gravy)",
    category: "chinese-veg",
    price: "₹319",
    priceNum: 319,
    isVeg: true,
    isSpicy: true,
    description: "Tender button mushrooms tossed with green chilies, onions and garlic soy.",
  },
  {
    id: "cv-10",
    name: "Mushroom Duplex",
    category: "chinese-veg",
    price: "₹329",
    priceNum: 329,
    isVeg: true,
    isSignature: true,
    description: "Stuffed mushroom caps filled with spiced paneer, coated in batter and crisp fried.",
  },
  {
    id: "cv-11",
    name: "Honey Chilly Potato",
    category: "chinese-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Crispy potato fingers tossed in honey, sesame seeds and spicy chili sauce.",
  },
  {
    id: "cv-12",
    name: "Hara Bhara Kabab",
    category: "chinese-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Spinach, green pea and paneer patties pan-grilled with aromatic garam masala.",
  },

  // ── CHINESE NON-VEG (Page 3) ────────────────
  {
    id: "cnv-1",
    name: "Get 2 Gather Special Chicken (B/L) (Dry)",
    category: "chinese-non-veg",
    price: "₹499",
    priceNum: 499,
    isVeg: false,
    isSignature: true,
    description: "Our signature boneless chicken specialty tossed with chef's secret oriental spices.",
  },
  {
    id: "cnv-2",
    name: "Chicken Mandarin (Dry / B/L)",
    category: "chinese-non-veg",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    description: "Fried chicken, red, yellow and green capsicum tossed in savory black bean sauce.",
  },
  {
    id: "cnv-3",
    name: "Crispy Fried Chicken (B/L)",
    category: "chinese-non-veg",
    price: "₹359",
    priceNum: 359,
    isVeg: false,
    description: "Extra crispy boneless chicken tenders seasoned with oriental spices.",
  },
  {
    id: "cnv-4",
    name: "Crispy Honey Chicken (B/L)",
    category: "chinese-non-veg",
    price: "₹359",
    priceNum: 359,
    isVeg: false,
    description: "Crispy boneless chicken tossed with pure honey and toasted sesame seeds.",
  },
  {
    id: "cnv-5",
    name: "Lemon Chicken (W/Bone / Boneless) (Dry / Gravy)",
    category: "chinese-non-veg",
    price: "₹359",
    priceNum: 359,
    isVeg: false,
    description: "Tender chicken pieces coated in zesty lemon glaze.",
  },
  {
    id: "cnv-6",
    name: "Garlic Chicken (W/Bone / Boneless) (Dry / Gravy)",
    category: "chinese-non-veg",
    price: "₹359",
    priceNum: 359,
    isVeg: false,
    description: "Chicken pieces tossed in fragrant roasted garlic and soy sauce.",
  },
  {
    id: "cnv-7",
    name: "Chilly Chicken (W/Bone / Boneless) (Dry / Gravy)",
    category: "chinese-non-veg",
    price: "₹359",
    priceNum: 359,
    isVeg: false,
    isSpicy: true,
    isSignature: true,
    description: "All-time favorite Indo-Chinese chili chicken with diced capsicum and onions.",
  },
  {
    id: "cnv-8",
    name: "Chicken Manchurian (Dry / Gravy)",
    category: "chinese-non-veg",
    price: "₹359",
    priceNum: 359,
    isVeg: false,
    description: "Fried chicken bites smothered in garlic-coriander dark Manchurian sauce.",
  },
  {
    id: "cnv-9",
    name: "Cream Chicken",
    category: "chinese-non-veg",
    price: "₹369",
    priceNum: 369,
    isVeg: false,
    description: "Succulent chicken cooked in rich fresh cream and mild seasonings.",
  },
  {
    id: "cnv-10",
    name: "Golden Fried Chicken",
    category: "chinese-non-veg",
    price: "₹369",
    priceNum: 369,
    isVeg: false,
    description: "Deep-fried chicken pieces with crunchy golden crust served with hot garlic dip.",
  },

  // ── FISH (Page 3) ───────────────────────────
  {
    id: "fsh-1",
    name: "Fish Amritsari",
    category: "fish",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    isSignature: true,
    description: "Fresh river sole fish marinated in Punjabi spices, ajwain and batter fried to crisp perfection.",
  },
  {
    id: "fsh-2",
    name: "Fish Finger",
    category: "fish",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    description: "Delicate fish batons crumb coated and fried, served with tartar sauce.",
  },
  {
    id: "fsh-3",
    name: "Fried Fish",
    category: "fish",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    description: "Traditional marinated fried fish with lemon wedges and mint chutney.",
  },
  {
    id: "fsh-4",
    name: "Fish Chilly",
    category: "fish",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    isSpicy: true,
    description: "Battered fish tossed with spicy green chilies, onions and dark soy.",
  },
  {
    id: "fsh-5",
    name: "Lemon Fish",
    category: "fish",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    description: "Delicate fish fillets cooked in refreshing lemon butter garlic sauce.",
  },
  {
    id: "fsh-6",
    name: "Garlic Fish",
    category: "fish",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    description: "Tender fish fillets cooked in aromatic garlic gravy.",
  },

  // ── TANDOORI SNACKS VEG (Page 3) ────────────
  {
    id: "tsv-1",
    name: "Paneer Tikka",
    category: "tandoori-veg",
    price: "₹259",
    priceNum: 259,
    isVeg: true,
    isSignature: true,
    description: "Cubes of fresh paneer marinated in yogurt and tandoori spices, skewered over charcoal.",
  },
  {
    id: "tsv-2",
    name: "Paneer Irani Tikka",
    category: "tandoori-veg",
    price: "₹289",
    priceNum: 289,
    isVeg: true,
    description: "Paneer cubes marinated in rich cashew paste, cheese and exotic saffron.",
  },
  {
    id: "tsv-3",
    name: "Paneer Haryali Tikka",
    category: "tandoori-veg",
    price: "₹289",
    priceNum: 289,
    isVeg: true,
    description: "Paneer marinated in fresh mint, coriander paste, roasted in tandoor.",
  },
  {
    id: "tsv-4",
    name: "Paneer Malai Tikka",
    category: "tandoori-veg",
    price: "₹289",
    priceNum: 289,
    isVeg: true,
    description: "Melt-in-mouth cottage cheese marinated in fresh cream, cardamom and cheese.",
  },
  {
    id: "tsv-5",
    name: "Mushroom Makhmali",
    category: "tandoori-veg",
    price: "₹289",
    priceNum: 289,
    isVeg: true,
    description: "Velvety button mushrooms stuffed with spiced cottage cheese roasted over live coals.",
  },
  {
    id: "tsv-6",
    name: "Stuffed Mushroom Tikka",
    category: "tandoori-veg",
    price: "₹289",
    priceNum: 289,
    isVeg: true,
    description: "Juicy mushrooms packed with herbs and paneer, char-grilled in tandoor.",
  },
  {
    id: "tsv-7",
    name: "Veg Seekh Kebab",
    category: "tandoori-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Minced vegetable and cottage cheese skewers spiced with cumin and roasted over coals.",
  },
  {
    id: "tsv-8",
    name: "Plate AE KHAS",
    category: "tandoori-veg",
    price: "₹549",
    priceNum: 549,
    isVeg: true,
    isSignature: true,
    description: "The Grand Royal Vegetarian Tandoori Platter: Assortment of Paneer Tikka, Mushroom, Seekh Kebab & Champ.",
  },
  {
    id: "tsv-9",
    name: "Tandoori Champ",
    category: "tandoori-veg",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    description: "Soya chaap marinated in spiced tandoori yogurt marinade and grilled in the tandoor.",
  },
  {
    id: "tsv-10",
    name: "Malai Champ",
    category: "tandoori-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Tender soya chaap coated in luscious cream, cashew nut paste and mild spices.",
  },
  {
    id: "tsv-11",
    name: "Mushroom Tikka",
    category: "tandoori-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Fresh button mushrooms coated with spicy red tandoori masala.",
  },

  // ── FISH TANDOORI (Page 4) ──────────────────
  {
    id: "ft-1",
    name: "Fish Tikka",
    category: "fish-tandoori",
    price: "₹459",
    priceNum: 459,
    isVeg: false,
    isSignature: true,
    description: "Succulent boneless fish fillets marinated in mustard oil, yogurt and spices, clay oven roasted.",
  },
  {
    id: "ft-2",
    name: "Fish Ajwani Tikka",
    category: "fish-tandoori",
    price: "₹459",
    priceNum: 459,
    isVeg: false,
    description: "Delicate fish marinated with carom seeds (ajwain), lemon and roasted over charcoal.",
  },
  {
    id: "ft-3",
    name: "Fish Achari",
    category: "fish-tandoori",
    price: "₹459",
    priceNum: 459,
    isVeg: false,
    isSpicy: true,
    description: "Fish fillets infused with tangy pickling spices and char-grilled.",
  },
  {
    id: "ft-4",
    name: "Fish Malai Tikka",
    category: "fish-tandoori",
    price: "₹459",
    priceNum: 459,
    isVeg: false,
    description: "Tender boneless fish steeped in cream, cheese and fragrant green cardamom.",
  },

  // ── MAIN COURSE VEG (Page 4) ────────────────
  {
    id: "mcv-1",
    name: "Dal Makhani",
    category: "main-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    isSignature: true,
    description: "Black lentils slow-simmered overnight with butter, fresh tomato puree and heavy cream.",
  },
  {
    id: "mcv-2",
    name: "Yellow Dal Tadka",
    category: "main-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Yellow arhar lentils tempered with desi ghee, cumin, garlic, onions and tomatoes.",
  },
  {
    id: "mcv-3",
    name: "Black Dal Tadka",
    category: "main-veg",
    price: "₹229",
    priceNum: 229,
    isVeg: true,
    description: "Whole black urad dal tempered with aromatic Punjabi tadka.",
  },
  {
    id: "mcv-4",
    name: "Paneer Makhani",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Soft paneer cubes simmered in velvety, buttery tomato and cashew gravy.",
  },
  {
    id: "mcv-5",
    name: "Kadai Paneer",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    isSpicy: true,
    isSignature: true,
    description: "Paneer cooked with bell peppers, onions and freshly ground kadai spices.",
  },
  {
    id: "mcv-6",
    name: "Paneer Do Piaza",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Paneer cooked with double the quantity of caramelized and sautéed crunchy onions.",
  },
  {
    id: "mcv-7",
    name: "Paneer Lababdar",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Luscious Mughlai dish with grated and cubed paneer in a rich tomato-onion gravy.",
  },
  {
    id: "mcv-8",
    name: "Palak Paneer",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Fresh cottage cheese cubes in smooth spiced spinach puree.",
  },
  {
    id: "mcv-9",
    name: "Mutter Paneer",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Classic combination of green peas and cottage cheese in spiced tomato sauce.",
  },
  {
    id: "mcv-10",
    name: "Paneer Bhurji",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Scrambled fresh cottage cheese cooked with chopped onions, tomatoes and green chilies.",
  },
  {
    id: "mcv-11",
    name: "Malai Kofta",
    category: "main-veg",
    price: "₹299",
    priceNum: 299,
    isVeg: true,
    isSignature: true,
    description: "Stuffed potato and paneer dumplings gently simmered in a creamy golden cashew gravy.",
  },
  {
    id: "mcv-12",
    name: "Paneer Tikka Butter Masala",
    category: "main-veg",
    price: "₹299",
    priceNum: 299,
    isVeg: true,
    isSignature: true,
    description: "Charcoal-grilled paneer tikka tossed in rich buttery tomato masala gravy.",
  },
  {
    id: "mcv-13",
    name: "Mix Vegetables",
    category: "main-veg",
    price: "₹209",
    priceNum: 209,
    isVeg: true,
    description: "Seasonal garden vegetables cooked together in a spiced home-style gravy.",
  },
  {
    id: "mcv-14",
    name: "Veg. Jalfrezi",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Julienned vegetables stir-fried with onions, capsicum and tangy tomato sauce.",
  },
  {
    id: "mcv-15",
    name: "Mushroom Mattar",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Button mushrooms and green peas simmered in onion-tomato gravy.",
  },
  {
    id: "mcv-16",
    name: "Mushroom Do Piaza",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Tender button mushrooms cooked with lots of crunchy onions and spices.",
  },
  {
    id: "mcv-17",
    name: "Mushroom Masala",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Fresh mushrooms cooked in a thick spicy masala gravy.",
  },
  {
    id: "mcv-18",
    name: "Mushroom Matter Methi Malai",
    category: "main-veg",
    price: "₹299",
    priceNum: 299,
    isVeg: true,
    isSignature: true,
    description: "Mushrooms, peas and fenugreek leaves cooked in fragrant white cashew cream gravy.",
  },
  {
    id: "mcv-19",
    name: "Tawa Mushroom",
    category: "main-veg",
    price: "₹279",
    priceNum: 279,
    isVeg: true,
    description: "Mushrooms roasted on an iron tawa with crushed spices and fresh ginger.",
  },
  {
    id: "mcv-20",
    name: "Palak Corn",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Sweet corn kernels in velvety garlic-infused spinach puree.",
  },
  {
    id: "mcv-21",
    name: "Matter Methi Malai",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Fresh fenugreek and green peas in rich creamy gravy.",
  },
  {
    id: "mcv-22",
    name: "Masala Champ",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Soybean chaap pieces cooked in spicy onion-tomato gravy.",
  },
  {
    id: "mcv-23",
    name: "Kadai Champ",
    category: "main-veg",
    price: "₹249",
    priceNum: 249,
    isVeg: true,
    description: "Soya chaap cooked with bell peppers and freshly pounded coriander seeds.",
  },
  {
    id: "mcv-24",
    name: "Channa Masala",
    category: "main-veg",
    price: "₹239",
    priceNum: 239,
    isVeg: true,
    description: "Authentic spicy Amritsari chickpea curry cooked with pomegranate seeds and ginger.",
  },

  // ── MAIN COURSE NON-VEG (Page 4) ────────────
  {
    id: "mcnv-1",
    name: "Butter Chicken",
    category: "main-non-veg",
    price: "Half ₹369 / Full ₹579",
    priceNum: 369,
    isVeg: false,
    isSignature: true,
    description: "World-famous tandoori chicken simmered in rich creamy tomato, butter and cashew gravy.",
  },
  {
    id: "mcnv-2",
    name: "Kadai Chicken",
    category: "main-non-veg",
    price: "Half ₹369 / Full ₹579",
    priceNum: 369,
    isVeg: false,
    isSpicy: true,
    description: "Chicken pieces braised with bell peppers, onions and crushed dry spices in a wok.",
  },
  {
    id: "mcnv-3",
    name: "Chicken Rara",
    category: "main-non-veg",
    price: "Half ₹399 / Full ₹599",
    priceNum: 399,
    isVeg: false,
    isSignature: true,
    description: "Chicken pieces slow-cooked in rich minced chicken keema gravy.",
  },
  {
    id: "mcnv-4",
    name: "Masala Chicken",
    category: "main-non-veg",
    price: "Half ₹369 / Full ₹579",
    priceNum: 369,
    isVeg: false,
    description: "Chicken simmered in traditional spicy brown onion and tomato masala.",
  },
  {
    id: "mcnv-5",
    name: "Home Style Chicken Curry",
    category: "main-non-veg",
    price: "Half ₹369 / Full ₹579",
    priceNum: 369,
    isVeg: false,
    description: "Hearty Punjabi tari wala chicken cooked just like home with aromatic spices.",
  },
  {
    id: "mcnv-6",
    name: "Chicken Do Piaza",
    category: "main-non-veg",
    price: "Half ₹369 / Full ₹579",
    priceNum: 369,
    isVeg: false,
    description: "Tender chicken cooked with sweet shallots and crisp caramelized onions.",
  },
  {
    id: "mcnv-7",
    name: "Chicken Tikka Butter Masala",
    category: "main-non-veg",
    price: "Half ₹389 / Full ₹579",
    priceNum: 389,
    isVeg: false,
    isSignature: true,
    description: "Boneless charcoal-roasted chicken tikka in luxurious makhani gravy.",
  },
  {
    id: "mcnv-8",
    name: "Get 2 Gather Chicken",
    category: "main-non-veg",
    price: "₹449",
    priceNum: 449,
    isVeg: false,
    isSignature: true,
    description: "Chef's exclusive house chicken preparation with secret blend of Punjabi herbs.",
  },
  {
    id: "mcnv-9",
    name: "Chicken Tikka Lababdar",
    category: "main-non-veg",
    price: "₹389",
    priceNum: 389,
    isVeg: false,
    description: "Smoky chicken tikka in thick tomato gravy enriched with cheese.",
  },
  {
    id: "mcnv-10",
    name: "Punjabi Kukad Masala",
    category: "main-non-veg",
    price: "₹389",
    priceNum: 389,
    isVeg: false,
    isSpicy: true,
    description: "Authentic rustic country chicken curry with robust Punjabi tadka.",
  },

  // ── MUTTON SPECIAL (Page 4) ─────────────────
  {
    id: "mut-1",
    name: "Mutton Roganjosh",
    category: "mutton",
    price: "₹399",
    priceNum: 399,
    isVeg: false,
    isSignature: true,
    description: "Kashmiri delicacy: tender baby lamb slow-braised with ratan jot and aromatic spices.",
  },
  {
    id: "mut-2",
    name: "Kadai Mutton",
    category: "mutton",
    price: "₹399",
    priceNum: 399,
    isVeg: false,
    isSpicy: true,
    description: "Succulent mutton braised in an iron kadai with freshly ground coriander and peppers.",
  },
  {
    id: "mut-3",
    name: "Mutton Curry",
    category: "mutton",
    price: "₹399",
    priceNum: 399,
    isVeg: false,
    description: "Slow-cooked tender goat meat in rich caramelized onion gravy.",
  },
  {
    id: "mut-4",
    name: "Rara Mutton",
    category: "mutton",
    price: "₹469",
    priceNum: 469,
    isVeg: false,
    isSignature: true,
    description: "Royal preparation: succulent mutton chunks cooked inside spiced keema gravy.",
  },

  // ── FISH MAIN (Page 4) ──────────────────────
  {
    id: "fshm-1",
    name: "Fish Curry",
    category: "fish",
    price: "₹389",
    priceNum: 389,
    isVeg: false,
    description: "Tender river fish simmered in tangy Punjabi onion-mustard gravy.",
  },
  {
    id: "fshm-2",
    name: "Fish Tikka Butter Masala",
    category: "fish",
    price: "₹489",
    priceNum: 489,
    isVeg: false,
    isSignature: true,
    description: "Charcoal roasted fish tikka in smooth velvety butter gravy.",
  },
  {
    id: "fshm-3",
    name: "Fish Kadai",
    category: "fish",
    price: "₹389",
    priceNum: 389,
    isVeg: false,
    isSpicy: true,
    description: "Fish fillets cooked with bell peppers and roasted spices.",
  },

  // ── RICE & BIRYANI (Page 4 & Page 5) ────────
  {
    id: "rb-1",
    name: "Jeera Rice",
    category: "rice-biryani",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    description: "Fragrant basmati rice tempered with roasted cumin seeds and desi ghee.",
  },
  {
    id: "rb-2",
    name: "Veg Pulao",
    category: "rice-biryani",
    price: "₹189",
    priceNum: 189,
    isVeg: true,
    description: "Aromatic basmati rice cooked with garden fresh vegetables and whole spices.",
  },
  {
    id: "rb-3",
    name: "Plain Rice",
    category: "rice-biryani",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    description: "Steamed fluffy long-grain basmati rice.",
  },
  {
    id: "rb-4",
    name: "Peas Pulao",
    category: "rice-biryani",
    price: "₹199",
    priceNum: 199,
    isVeg: true,
    description: "Basmati rice cooked with sweet green peas and whole cardamom.",
  },
  {
    id: "rb-5",
    name: "Kashmiri Pulao",
    category: "rice-biryani",
    price: "₹199",
    priceNum: 199,
    isVeg: true,
    description: "Sweet and savoury pulao garnished with dried fruits, nuts and fresh pomegranate.",
  },
  {
    id: "rb-6",
    name: "Veg Biryani with Raita",
    category: "rice-biryani",
    price: "₹299",
    priceNum: 299,
    isVeg: true,
    description: "Layered basmati rice with spiced seasonal vegetables, served with chilled raita.",
  },
  {
    id: "rb-7",
    name: "Dum Veg Biryani with Raita",
    category: "rice-biryani",
    price: "₹349",
    priceNum: 349,
    isVeg: true,
    isSignature: true,
    description: "Slow sealed handi dum cooked vegetable biryani infused with saffron and kewra.",
  },
  {
    id: "rb-8",
    name: "Chicken Biryani with Raita",
    category: "rice-biryani",
    price: "₹379",
    priceNum: 379,
    isVeg: false,
    description: "Marinated chicken pieces layered with aromatic basmati rice, served with raita.",
  },
  {
    id: "rb-9",
    name: "Chicken Dum Biryani with Raita",
    category: "rice-biryani",
    price: "₹399",
    priceNum: 399,
    isVeg: false,
    isSignature: true,
    description: "Dum-cooked Hyderabadi-style aromatic saffron chicken biryani with chilled raita.",
  },

  // ── SALAD & RAITA (Page 5) ──────────────────
  {
    id: "sr-1",
    name: "Garden Fresh Green Salad",
    category: "salad-raita",
    price: "₹99",
    priceNum: 99,
    isVeg: true,
    description: "Freshly sliced cucumbers, tomatoes, carrots, radishes and green chilies.",
  },
  {
    id: "sr-2",
    name: "Russian Salad",
    category: "salad-raita",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    description: "Diced boiled vegetables and pineapple tossed in creamy mayonnaise.",
  },
  {
    id: "sr-3",
    name: "Cucumber Salad",
    category: "salad-raita",
    price: "₹89",
    priceNum: 89,
    isVeg: true,
    description: "Crisp cucumber rings with lemon and rock salt.",
  },
  {
    id: "sr-4",
    name: "Cream Kachumber",
    category: "salad-raita",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    description: "Finely diced veggies dressed in seasoned cream sauce.",
  },
  {
    id: "sr-5",
    name: "Get 2 Gather Healthy Salad",
    category: "salad-raita",
    price: "₹199",
    priceNum: 199,
    isVeg: true,
    isSignature: true,
    description: "Nutritious mix of sprouts, paneer, greens, walnuts, seeds and lemon olive oil dressing.",
  },
  {
    id: "sr-6",
    name: "Macaroni Peanut Salad",
    category: "salad-raita",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    description: "Boiled macaroni and crunchy peanuts tossed with herbs.",
  },
  {
    id: "sr-7",
    name: "Mix Raita",
    category: "salad-raita",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Whisked curd with chopped onions, tomatoes, green chilies and roasted cumin.",
  },
  {
    id: "sr-8",
    name: "Boondi Raita",
    category: "salad-raita",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Crispy chickpea flour droplets soaked in spiced chilled yogurt.",
  },
  {
    id: "sr-9",
    name: "Pineapple Raita",
    category: "salad-raita",
    price: "₹169",
    priceNum: 169,
    isVeg: true,
    description: "Sweet juicy pineapple chunks in sweetened, chilled creamy curd.",
  },
  {
    id: "sr-10",
    name: "Mint Raita",
    category: "salad-raita",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Cooling fresh garden mint and yogurt raita.",
  },

  // ── ASSORTED BREADS (Page 5) ────────────────
  {
    id: "brd-1",
    name: "Plain Roti",
    category: "breads",
    price: "₹20",
    priceNum: 20,
    isVeg: true,
    description: "Whole wheat bread baked fresh in charcoal clay tandoor.",
  },
  {
    id: "brd-2",
    name: "Butter Roti",
    category: "breads",
    price: "₹25",
    priceNum: 25,
    isVeg: true,
    description: "Tandoori wheat roti brushed with pure desi butter.",
  },
  {
    id: "brd-3",
    name: "Missi Roti",
    category: "breads",
    price: "₹39",
    priceNum: 39,
    isVeg: true,
    isSignature: true,
    description: "Gram flour and whole wheat flatbread spiced with ajwain, onions and green chilies.",
  },
  {
    id: "brd-4",
    name: "Plain Naan",
    category: "breads",
    price: "₹49",
    priceNum: 49,
    isVeg: true,
    description: "Soft leavened refined flour bread baked in the clay oven.",
  },
  {
    id: "brd-5",
    name: "Butter Naan",
    category: "breads",
    price: "₹69",
    priceNum: 69,
    isVeg: true,
    description: "Tandoor-baked naan brushed with melted butter.",
  },
  {
    id: "brd-6",
    name: "Lacha Parantha",
    category: "breads",
    price: "₹55",
    priceNum: 55,
    isVeg: true,
    description: "Multi-layered flaky whole wheat parantha brushed with butter.",
  },
  {
    id: "brd-7",
    name: "Pudina Parantha",
    category: "breads",
    price: "₹55",
    priceNum: 55,
    isVeg: true,
    description: "Layered tandoori parantha dusted with dried mint leaves.",
  },
  {
    id: "brd-8",
    name: "Garlic Naan",
    category: "breads",
    price: "₹79",
    priceNum: 79,
    isVeg: true,
    isSignature: true,
    description: "Leavened naan topped with minced roasted garlic, butter and fresh coriander.",
  },
  {
    id: "brd-9",
    name: "Mirchi Parantha (Red / Green)",
    category: "breads",
    price: "₹55",
    priceNum: 55,
    isVeg: true,
    isSpicy: true,
    description: "Flaky parantha stuffed with crushed red or green chilies.",
  },
  {
    id: "brd-10",
    name: "Stuffed Kulcha",
    category: "breads",
    price: "₹89",
    priceNum: 89,
    isVeg: true,
    description: "Amritsari style kulcha stuffed with spiced potatoes and onions.",
  },
  {
    id: "brd-11",
    name: "Cheese Naan with Gravy",
    category: "breads",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    isSignature: true,
    description: "Freshly baked naan stuffed with gooey cheese, served with rich makhani gravy.",
  },
  {
    id: "brd-12",
    name: "Ajwani Roti",
    category: "breads",
    price: "₹25",
    priceNum: 25,
    isVeg: true,
    description: "Tandoori roti infused with aromatic carom seeds.",
  },

  // ── DESSERTS (Page 5) ───────────────────────
  {
    id: "des-1",
    name: "Hot Gulab Jamun",
    category: "desserts",
    price: "₹89",
    priceNum: 89,
    isVeg: true,
    isSignature: true,
    description: "Golden fried milk-solid dumplings soaked in warm rose and cardamom sugar syrup.",
  },
  {
    id: "des-2",
    name: "Choice of Ice Cream",
    category: "desserts",
    price: "₹89",
    priceNum: 89,
    isVeg: true,
    description: "Scoop of Vanilla, Strawberry, Butter Scotch or Rich Chocolate.",
  },
  {
    id: "des-3",
    name: "Tooti Chocolate Frooti Large",
    category: "desserts",
    price: "₹99",
    priceNum: 99,
    isVeg: true,
    description: "Ice cream sundae layered with chocolate fudge, tutty-fruity candies and nuts.",
  },
  {
    id: "des-4",
    name: "Hot Chocolate Fudge",
    category: "desserts",
    price: "₹149",
    priceNum: 149,
    isVeg: true,
    isSignature: true,
    description: "Vanilla ice cream smothered in piping hot dark chocolate fudge sauce with roasted nuts.",
  },
  {
    id: "des-5",
    name: "Tooti Frooti Small",
    category: "desserts",
    price: "₹129",
    priceNum: 129,
    isVeg: true,
    description: "Classic ice cream cup with fruit pearls and strawberry swirl.",
  },

  // ── BAR & BEVERAGES ─────────────────────────
  {
    id: "bev-1",
    name: "Hot Artisanal Coffee",
    category: "bar-beverages",
    price: "₹50",
    priceNum: 50,
    isVeg: true,
    description: "Freshly ground roasted bean espresso frothed with steamed milk.",
    image: "/uploads/gtg-coffee-cappuccino.jpg",
  },
  {
    id: "bev-2",
    name: "Cold Coffee",
    category: "bar-beverages",
    price: "₹90",
    priceNum: 90,
    isVeg: true,
    description: "Chilled blended coffee with rich chocolate syrup drizzle.",
  },
  {
    id: "bev-3",
    name: "Cold Coffee with Ice Cream",
    category: "bar-beverages",
    price: "₹150",
    priceNum: 150,
    isVeg: true,
    isSignature: true,
    description: "Thick decadent cold coffee topped with a creamy vanilla ice cream scoop.",
  },
  {
    id: "bev-4",
    name: "Punjabi Sweet / Salted Lassi",
    category: "bar-beverages",
    price: "₹40",
    priceNum: 40,
    isVeg: true,
    description: "Traditional churned thick yogurt lassi served chilled.",
  },
  {
    id: "bev-5",
    name: "Kingfisher Draught Beer",
    category: "bar-beverages",
    price: "Mug ₹190 / Jug ₹700 / Pitcher ₹1350",
    priceNum: 190,
    description: "Fresh chilled draught beer straight from the tap.",
  },
  {
    id: "bev-6",
    name: "Beach Beauty Draught Beer",
    category: "bar-beverages",
    price: "Mug ₹210 / Jug ₹750 / Pitcher ₹1400",
    priceNum: 210,
    description: "Crisp draught beer poured fresh at the Get To Gether Lounge.",
  },
  {
    id: "bev-7",
    name: "Kingfisher Ultra / Heineken / Budweiser",
    category: "bar-beverages",
    price: "₹400 / Bottle",
    priceNum: 400,
    description: "Premium chilled bottled beers (Carlsberg, Corona Extra, Miller Ace also available).",
  },
  {
    id: "bev-8",
    name: "Scotch & Whiskeys",
    category: "bar-beverages",
    price: "From ₹80 (30ml) / ₹120 (60ml)",
    priceNum: 80,
    description: "VAT 69, Black & White, 100 Pipers, Teacher's Highland, Black Dog Centenary, Royal Stag.",
  },
];
